import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Bell,
  Box,
  Building2,
  Calendar,
  Car,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Crown,
  EllipsisVertical,
  Eye,
  EyeOff,
  Feather,
  FileBadge,
  FileText,
  Fingerprint,
  FlaskConical,
  Folder,
  Globe,
  HeartPulse,
  Hexagon,
  Hourglass,
  House,
  type IconNode,
  IdCard,
  Inbox,
  Info,
  KeyRound,
  Languages,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Minus,
  Monitor,
  Moon,
  Package,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldOff,
  Sparkles,
  Store,
  Sun,
  TimerOff,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  UserCog,
  UserPlus,
  UserRound,
  Users,
  X,
} from 'lucide';

interface IconDefinition {
  readonly node: IconNode;
  /** Points along the reading direction (arrows, chevrons): mirrored in RTL (docs/ARCHITECTURE.md §17, §26). */
  readonly directional: boolean;
}

const icon = (node: IconNode, directional = false): IconDefinition => ({ node, directional });

/**
 * The Nawara icon set: Lucide (ISC), brand board "Icon style (Lucide based)". Only registered icons are bundled;
 * add an entry here to use a new one. Names are Lucide's kebab-case names.
 */
export const NW_ICONS = {
  'arrow-left': icon(ArrowLeft, true),
  'arrow-right': icon(ArrowRight, true),
  'arrow-up': icon(ArrowUp),
  award: icon(Award),
  'badge-check': icon(BadgeCheck),
  bell: icon(Bell),
  box: icon(Box),
  'building-2': icon(Building2),
  calendar: icon(Calendar),
  car: icon(Car),
  'chart-column': icon(ChartColumn),
  'chart-line': icon(ChartLine),
  'chart-no-axes-column': icon(ChartNoAxesColumn),
  check: icon(Check),
  'chevron-down': icon(ChevronDown),
  'chevron-right': icon(ChevronRight, true),
  'chevrons-up-down': icon(ChevronsUpDown),
  'circle-alert': icon(CircleAlert),
  'circle-check': icon(CircleCheck),
  'circle-x': icon(CircleX),
  'clipboard-list': icon(ClipboardList),
  clock: icon(Clock),
  'cloud-off': icon(CloudOff),
  copy: icon(Copy),
  'credit-card': icon(CreditCard),
  crown: icon(Crown),
  'ellipsis-vertical': icon(EllipsisVertical),
  eye: icon(Eye),
  'eye-off': icon(EyeOff),
  feather: icon(Feather),
  'file-badge': icon(FileBadge),
  'file-text': icon(FileText),
  fingerprint: icon(Fingerprint),
  'flask-conical': icon(FlaskConical),
  folder: icon(Folder),
  globe: icon(Globe),
  'heart-pulse': icon(HeartPulse),
  hexagon: icon(Hexagon),
  hourglass: icon(Hourglass),
  house: icon(House),
  'id-card': icon(IdCard),
  inbox: icon(Inbox),
  info: icon(Info),
  'key-round': icon(KeyRound),
  languages: icon(Languages),
  'lock-keyhole': icon(LockKeyhole),
  'log-out': icon(LogOut, true),
  mail: icon(Mail),
  menu: icon(Menu),
  minus: icon(Minus),
  monitor: icon(Monitor),
  moon: icon(Moon),
  package: icon(Package),
  palette: icon(Palette),
  pencil: icon(Pencil),
  plus: icon(Plus),
  'refresh-cw': icon(RefreshCw),
  'rotate-ccw': icon(RotateCcw),
  'scroll-text': icon(ScrollText),
  search: icon(Search),
  send: icon(Send),
  settings: icon(Settings),
  'shield-check': icon(ShieldCheck),
  'shield-off': icon(ShieldOff),
  sparkles: icon(Sparkles),
  store: icon(Store),
  sun: icon(Sun),
  'timer-off': icon(TimerOff),
  trash: icon(Trash),
  'trending-down': icon(TrendingDown),
  'trending-up': icon(TrendingUp),
  'triangle-alert': icon(TriangleAlert),
  'user-cog': icon(UserCog),
  'user-plus': icon(UserPlus),
  'user-round': icon(UserRound),
  users: icon(Users),
  x: icon(X),
} as const satisfies Record<string, IconDefinition>;

export type NwIconName = keyof typeof NW_ICONS;
