// GENERATED by tools/brand/recolor_artwork.py: do not edit by hand.
import type { AccentPalette, ResolvedTheme } from './theme.service';

/**
 * The botanical artwork of each accent palette and theme: the single palette-to-artwork mapping. The CSS tokens
 * (tokens/_brand-artwork.scss) are generated from the same data; ThemeService preloads these files before a switch.
 */
export interface PaletteArtwork extends Record<
  ResolvedTheme,
  { readonly full: string; readonly corner: string }
> {
  /**
   * The browser-tab icon in the palette's colours, per resolved appearance: the paper circle (light) and the ink
   * circle (dark). One file per palette and appearance, so each switch is a new URL, never a stale cached icon.
   */
  readonly favicon: Readonly<Record<ResolvedTheme, string>>;
}

export const PALETTE_ARTWORK: Readonly<Record<AccentPalette, PaletteArtwork>> = {
  coral: {
    light: {
      full: '/illustrations/nawara-botanical-coral.png',
      corner: '/illustrations/nawara-botanical-corner-coral.png',
    },
    dark: {
      full: '/illustrations/nawara-botanical-dark.png',
      corner: '/illustrations/nawara-botanical-corner-dark.png',
    },
    favicon: { light: 'icons/favicon-coral-light.svg', dark: 'favicon.svg' },
  },
  rose: {
    light: {
      full: '/illustrations/nawara-botanical-rose.webp',
      corner: '/illustrations/nawara-botanical-corner-rose.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-rose-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-rose-dark.webp',
    },
    favicon: { light: 'icons/favicon-rose-light.svg', dark: 'icons/favicon-rose.svg' },
  },
  plum: {
    light: {
      full: '/illustrations/nawara-botanical-plum.webp',
      corner: '/illustrations/nawara-botanical-corner-plum.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-plum-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-plum-dark.webp',
    },
    favicon: { light: 'icons/favicon-plum-light.svg', dark: 'icons/favicon-plum.svg' },
  },
  indigo: {
    light: {
      full: '/illustrations/nawara-botanical-indigo.webp',
      corner: '/illustrations/nawara-botanical-corner-indigo.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-indigo-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-indigo-dark.webp',
    },
    favicon: { light: 'icons/favicon-indigo-light.svg', dark: 'icons/favicon-indigo.svg' },
  },
  teal: {
    light: {
      full: '/illustrations/nawara-botanical-teal.webp',
      corner: '/illustrations/nawara-botanical-corner-teal.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-teal-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-teal-dark.webp',
    },
    favicon: { light: 'icons/favicon-teal-light.svg', dark: 'icons/favicon-teal.svg' },
  },
  amber: {
    light: {
      full: '/illustrations/nawara-botanical-amber.webp',
      corner: '/illustrations/nawara-botanical-corner-amber.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-amber-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-amber-dark.webp',
    },
    favicon: { light: 'icons/favicon-amber-light.svg', dark: 'icons/favicon-amber.svg' },
  },
};
