// GENERATED by tools/brand/recolor_artwork.py: do not edit by hand.
import type { AccentPalette, ResolvedTheme } from './theme.service';

/**
 * The botanical artwork of each accent palette and theme: the single palette-to-artwork mapping. The CSS tokens
 * (tokens/_brand-artwork.scss) are generated from the same data; ThemeService preloads these files before a switch.
 */
export const PALETTE_ARTWORK: Readonly<
  Record<AccentPalette, Record<ResolvedTheme, { readonly full: string; readonly corner: string }>>
> = {
  coral: {
    light: {
      full: '/illustrations/nawara-botanical-coral.png',
      corner: '/illustrations/nawara-botanical-corner-coral.png',
    },
    dark: {
      full: '/illustrations/nawara-botanical-dark.png',
      corner: '/illustrations/nawara-botanical-corner-dark.png',
    },
  },
  rose: {
    light: {
      full: '/illustrations/nawara-botanical-rose.webp',
      corner: '/illustrations/nawara-botanical-corner-rose.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-rose-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-rose-dark.webp',
    },
  },
  plum: {
    light: {
      full: '/illustrations/nawara-botanical-plum.webp',
      corner: '/illustrations/nawara-botanical-corner-plum.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-plum-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-plum-dark.webp',
    },
  },
  indigo: {
    light: {
      full: '/illustrations/nawara-botanical-indigo.webp',
      corner: '/illustrations/nawara-botanical-corner-indigo.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-indigo-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-indigo-dark.webp',
    },
  },
  teal: {
    light: {
      full: '/illustrations/nawara-botanical-teal.webp',
      corner: '/illustrations/nawara-botanical-corner-teal.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-teal-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-teal-dark.webp',
    },
  },
  amber: {
    light: {
      full: '/illustrations/nawara-botanical-amber.webp',
      corner: '/illustrations/nawara-botanical-corner-amber.webp',
    },
    dark: {
      full: '/illustrations/nawara-botanical-amber-dark.webp',
      corner: '/illustrations/nawara-botanical-corner-amber-dark.webp',
    },
  },
};
